version: "3.8"

services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    environment:
      #- PAGID=10000
      #- PGID=1000
      #- PUID=1000
      - QBT_LEGAL_NOTICE=
      - QBT_WEBUI_PORT=8080
      #- TZ=UTC
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
      # for WebUI
      - 8080:8080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - <your_path>/config:/config
      - <your_path>/downloads:/downloads
