services:
  qbittorrent-nox:
      # for debugging
    cap_add:
      - SYS_PTRACE
    # additional arguments to `qbittorrent-nox`
    #command:
      #- --help
    container_name: qbittorrent-nox
    restart: unless-stopped
    environment:
      - PAGID=120
      - PGID=1001
      - PUID=113
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_TORRENTING_PORT=${QBT_TORRENTING_PORT}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=Europe/Budapest
      - UMASK=007
    image: qbittorrent-nox:${QBT_VERSION}
    ports:
      # for bittorrent traffic
      # - ${QBT_TORRENTING_PORT}:${QBT_TORRENTING_PORT}/tcp
      # - ${QBT_TORRENTING_PORT}:${QBT_TORRENTING_PORT}/udp
      # for WebUI
      #- ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/mnt
      - /etc/letsencrypt:/etc/letsencrypt
    network_mode: "host"
    mem_limit: "3G"
