version: "3.9"

services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    container_name: qbittorrent-nox
    restart: unless-stopped
    environment:
      - PAGID=120
      - PGID=1001
      - PUID=113
      - QBT_EULA=${QBT_EULA}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=Europe/Budapest
      - UMASK=007
    image: qbittorrent-nox:${QBT_VERSION}
    #ports:
      #for bittorrent traffic
      #- 44445:44445/tcp
      #- 44445:44445/udp
      # for WebUI
      #- ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/mnt
      - /etc/letsencrypt:/etc/letsencrypt
    network_mode: "host"
